name: Actualizar clasis.html

on:
  schedule:
    - cron: '0 18 * * 0'  # Domingos a las 20:00 CEST (18:00 UTC)
  push:
    branches:
      - main

jobs:
  update_clasis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Correcto: checkout del repositorio

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastf1  # Instalaci칩n de dependencias

    - name: Run f1_data.py para actualizar datos base
      run: python f1_data.py  # Comando para ejecutar el script f1_data.py

    - name: Run generar_tabla_campeonato.py para generar clasis.html
      run: python generar_tabla_campeonato.py  # Comando para ejecutar el script de la tabla

    - name: Esperar unos minutos
      run: sleep 30  # Comando para esperar 30 segundos

    - name: Limpiar posibles cambios no confirmados
      run: |
        git reset --hard
        git clean -fd  # Asegura que no haya cambios no confirmados

    - name: Pull changes from remote repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin main --no-rebase  # Pull de los cambios remotos antes de hacer el push

    - name: Commit y push de archivos actualizados
      run: |
        git add .
        git commit -m "Actualizaci칩n autom치tica de clasificaci칩n pilotos" || echo "Sin cambios para commitear"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main  # Push de cambios
