name: Actualización clases.html

on:
  schedule:
    - cron: '0 18 * * 0'  # Domingos a las 20:00 CEST (18:00 UTC)
  workflow_dispatch:  # Permite ejecución manual desde la interfaz

jobs:
  update_clasis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necesario para ver cambios en commits

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install fastf1 requests

    - name: Ejecutar actualización de datos
      run: python f1_data.py

    - name: Generar HTML
      run: python generar_tabla_campeonato.py

    - name: Verificar cambios reales
      id: check-changes
      run: |
        if git diff --exit-code; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "🟢 No hay cambios detectados"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "🔵 Cambios detectados:"
          git diff --name-only
        fi

    - name: Configurar Git
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}

    - name: Hacer commit y push
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git add .
        git commit -m "🤖 Actualización automática [skip ci]"
        git push origin main
        echo "🟢 Cambios subidos correctamente"

    - name: Notificar resultado
      run: |
        if [ "${{ steps.check-changes.outputs.changes }}" == "true" ]; then
          echo "✅ Se realizaron actualizaciones"
        else
          echo "ℹ️ No hubo cambios relevantes"
        fi