name: Actualización Automática de Clasis.html

on:
  schedule:
    - cron: '0 19 * * 0'  # Domingos a las 21:00 CEST (19:00 UTC)
  workflow_dispatch:  # Solo ejecución manual, no automática con push
  push:
    branches: 
      - 'never-run'  # Rama ficticia para que no se ejecute en push a main

jobs:
  update_clasis:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Evita ejecuciones infinitas

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # ¡Misma versión que usas localmente!
        
    - name: Crear y activar entorno virtual
      run: |
        python -m venv venv
        source venv/bin/activate  # ¡Clave para activar el venv!
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Ejecutar actualización de datos
      run: |
        source venv/bin/activate
        python f1_data.py

    - name: Generar HTML (formato protegido)
      run: |
        source venv/bin/activate
        python generar_tabla_campeonato.py
    

    - name: Verificar cambios reales
      id: check-changes
      run: |
        if git diff --quiet clasis.html; then
          echo "changes_detected=false" >> $GITHUB_OUTPUT
          echo "🟢 No hay cambios en clasis.html"
        else
          echo "changes_detected=true" >> $GITHUB_OUTPUT
          echo "🔵 Cambios detectados en:"
          git diff --name-only
        fi

    - name: Configurar Git (solo si hay cambios)
      if: steps.check-changes.outputs.changes_detected == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global core.autocrlf false  # Evita problemas de saltos de línea

    - name: Hacer Commit y Push (solo si hubo cambios)
      if: steps.check-changes.outputs.changes_detected == 'true'
      run: |
        git add clasis.html
        git commit -m "🤖 Actualización automática - $(date +'%d/%m/%Y') [skip ci]"
        git push origin main
        echo "🟢 Cambios subidos con formato preservado"

    - name: Notificar resultado
      run: |
        if [ "${{ steps.check-changes.outputs.changes_detected }}" == "true" ]; then
          echo "✅ Se actualizó clasis.html SIN perder formato"
        else
          echo "ℹ️ No hubo cambios en los datos fuente"
        fi
