name: Ejecutar motscrap.py los domingos

on:
  schedule:
    - cron: '0 20 * * 0'  # Domingos 19:00 UTC (21:00 hora Espa침a)
  workflow_dispatch:  # 游녣 Permite ejecuci칩n manual

jobs:
  run-motscrap:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 游녣 Solo si usas repositorio privado

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # 游녣 Aseg칰rate de que existe

      - name: Ejecutar motscrap.py
        run: python motscrap.py  # 游녣 Ejecuta desde la ra칤z del repositorio

      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Qualy/*.json
          git commit -m "Actualizaci칩n autom치tica Qualy"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 游녣 춰Imprescindible!