name: Ejecutar motscrap.py los domingos

on:
  schedule:
    - cron: '0 19 * * 0'  # Domingos 19:00 UTC (21:00 hora España)
  workflow_dispatch:  # 👈 Permite ejecución manual

jobs:
  run-motscrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # 👈 Asegúrate de que existe

      - name: Ejecutar motscrap.py
        run: python motscrap.py  # 👈 Ejecuta desde la raíz del repositorio