name: Ejecutar Script Motsprint

on:
  schedule:
    - cron: '0 21 * * 0'

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install requests  # Instalación forzada
          pip install -r requirements.txt  # Instala el resto
      
      - name: Ejecutar el script
        run: |
          source venv/bin/activate  # Reactiva el venv en ESTE paso
          python motsprint.py  # 👈 Ejecuta con el venv activo