name: Ejecutar Script Motsprint

on:
  schedule:
    - cron: '45 19 * * 0'
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 👈 Solo si usas repositorio privado

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python motsprint.py

      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Sprint/*.json
          git commit -m "Actualización automática Sprint"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 👈 ¡Imprescindible!