name: Ejecutar Script Motsprint

on:
  schedule:
    - cron: '0 21 * * 0'

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas numpy  # 👈 Instala solo lo esencial

      - name: Verificar instalación
        run: pip list  # 👈 Para ver qué paquetes se instalaron

      - name: Ejecutar el script
        run: python motsprint.py