name: Actualizar clasis.html

on:
  schedule:
  - cron: '7 7 * * 1'  # Lunes a las 7:07 UTC = 9:07 CEST (hora espa침ola)
  push:
    branches:
      - main  # O la rama que uses para subir tus cambios

jobs:
  update_clasis:
    runs-on: ubuntu-latest  # El sistema operativo donde se ejecuta el script

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Obtiene el c칩digo del repositorio

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Puedes especificar la versi칩n que uses

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastf1  # Instala FastF1 y cualquier otra dependencia que necesites

    - name: Run f1_data.py to update clasis.html
      run: |
        python f1_data.py  # Ejecuta tu script para generar el archivo HTML

    - name: Commit and push updated clasis.html
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add clasis.html
        git commit -m "Actualizaci칩n de clasis.html" || echo "Sin cambios para commitear"
        git push
