name: Actualizar Top Musical Diario

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  update-music:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar script
        run: python scripts/update_music.py

      - name: Commit y Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add top-musica.json
          git commit -m "Actualización automática: $(date +'%Y-%m-%d %H:%M')"
          git push
