name: Actualizar clasis.html

on:
  schedule:
    - cron: '00 11 * * 1'  # Lunes a las 12:30 AM CEST (10:30 PM UTC del domingo)
  push:
    branches:
      - main

jobs:
  update_clasis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastf1

    - name: Run f1_data.py to update clasis.html
      run: |
        python f1_data.py  # Ejecuta el script para actualizar el archivo

    - name: Wait for a few minutes
      run: sleep 180  # Espera 3 minutos para asegurarse de que todo esté listo antes del push

    - name: Commit and push all updated files (even if no changes to clasis.html)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .  # Añade todos los archivos modificados, no solo clasis.html
        git commit -m "Actualización de archivos con marca de tiempo" || echo "Sin cambios para commitear"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
